runtime: python37

instance_class: F2

env_variables:
  BUCKET_NAME: "meander_test_bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images
# TBH not sure if this will even work.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto